# Generated by Django 3.0.6 on 2020-05-29 19:07

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderName')),
            ],
            options={
                'verbose_name': 'LogsLog',
                'verbose_name_plural': 'LogsLogs',
            },
        ),
        migrations.CreateModel(
            name='LogsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Logs Tag',
                'verbose_name_plural': 'Logs Tags',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LogsTagAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LogsTag')),
            ],
            options={
                'verbose_name': 'Log Tag Assignment',
                'verbose_name_plural': 'Log Tag Assignments',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('assigned_tags', models.ManyToManyField(through='main.LogsTagAssign', to='main.LogsTag')),
                ('name', models.ManyToManyField(through='main.LogsLog', to='main.HeaderName')),
                ('value', models.ManyToManyField(through='main.LogsLog', to='main.HeaderValue')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-transaction'],
            },
        ),
        migrations.CreateModel(
            name='TagCryteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cryteria', models.TextField(validators=[main.models.validate_regex])),
                ('name_cryteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderValue')),
            ],
            options={
                'verbose_name': 'Tag Cryteria',
                'verbose_name_plural': 'Tag Cryterias',
            },
        ),
        migrations.AddField(
            model_name='logstagassign',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaction'),
        ),
        migrations.AddField(
            model_name='logstag',
            name='cryterias',
            field=models.ManyToManyField(to='main.TagCryteria'),
        ),
        migrations.CreateModel(
            name='LogsNote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('transaction', models.IntegerField(blank=True, default=1, null=True)),
                ('visitor_ip', models.GenericIPAddressField()),
                ('transactions', models.ManyToManyField(to='main.Transaction')),
            ],
            options={
                'verbose_name': 'LogsNote',
                'verbose_name_plural': 'LogsNotes',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='logslog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaction'),
        ),
        migrations.AddField(
            model_name='logslog',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderValue'),
        ),
        migrations.AddField(
            model_name='headervalue',
            name='header_names',
            field=models.ManyToManyField(through='main.LogsLog', to='main.HeaderName'),
        ),
    ]
