# Generated by Django 3.0.5 on 2020-04-21 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeaderValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cryteria', models.TextField()),
                ('tag', models.TextField()),
                ('description', models.TextField()),
                ('name_cryteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderName')),
            ],
            options={
                'verbose_name': 'Logs Tag',
                'verbose_name_plural': 'Logs Tags',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction', models.BigAutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='LogsTagAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LogsTag')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaction')),
            ],
            options={
                'verbose_name': 'Log Tag Assignment',
                'verbose_name_plural': 'Log Tag Assignments',
            },
        ),
        migrations.CreateModel(
            name='LogsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderName')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaction')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderValue')),
            ],
            options={
                'verbose_name': 'LogsLog',
                'verbose_name_plural': 'LogsLogs',
            },
        ),
        migrations.AddField(
            model_name='headervalue',
            name='header_names',
            field=models.ManyToManyField(through='main.LogsLog', to='main.HeaderName'),
        ),
    ]
