# Generated by Django 3.0.5 on 2020-04-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='assigned_tags',
            field=models.ManyToManyField(through='main.LogsTagAssign', to='main.LogsTag'),
        ),
    ]
