# Generated by Django 3.0.3 on 2020-02-27 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_value', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogsLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.BigIntegerField(default=1)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderName')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderValue')),
            ],
            options={
                'verbose_name': 'Logs Log',
                'verbose_name_plural': 'Logs Log',
                'get_latest_by': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='headervalue',
            name='header_names',
            field=models.ManyToManyField(through='main.LogsLog', to='main.HeaderName'),
        ),
    ]
