# Generated by Django 3.0.6 on 2020-05-30 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcryteria',
            name='name_cryteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderName'),
        ),
        migrations.AlterUniqueTogether(
            name='tagcryteria',
            unique_together={('name_cryteria', 'value_cryteria')},
        ),
    ]
