# Generated by Django 3.0.5 on 2020-04-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logslog',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='main.HeaderName'),
        ),
        migrations.AlterField(
            model_name='logslog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans', to='main.Transaction'),
        ),
        migrations.AlterField(
            model_name='logslog',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value', to='main.HeaderValue'),
        ),
    ]
