# Generated by Django 3.0.6 on 2020-05-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsnote',
            name='ip',
            field=models.TextField(),
        ),
    ]
