# Generated by Django 3.0.6 on 2020-05-26 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200526_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='server',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='visitor_ip',
        ),
    ]
