# Generated by Django 3.0.6 on 2020-05-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200527_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsnote',
            name='transaction',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
