# Generated by Django 3.0.5 on 2020-04-21 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200421_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logslog',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_test', to='main.HeaderName'),
        ),
        migrations.AlterField(
            model_name='logslog',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_test', to='main.HeaderValue'),
        ),
    ]
