# Generated by Django 3.0.4 on 2020-03-10 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200301_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_cryteria', models.TextField()),
                ('tag', models.TextField()),
                ('description', models.TextField()),
                ('name_cryteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderName')),
            ],
            options={
                'verbose_name': 'Logs Tag',
                'verbose_name_plural': 'Logs Tags',
            },
        ),
    ]
