# Generated by Django 3.0.5 on 2020-04-23 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transaction_assigned_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-transaction'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
