# Generated by Django 3.0.6 on 2020-05-31 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200530_1633'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tagcryteria',
            unique_together=set(),
        ),
    ]
