# Generated by Django 3.0.6 on 2020-06-01 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200531_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logstag',
            old_name='tag',
            new_name='tag_name',
        ),
    ]
