# Generated by Django 3.0.5 on 2020-04-23 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200423_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.ManyToManyField(through='main.LogsLog', to='main.HeaderName'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value',
            field=models.ManyToManyField(through='main.LogsLog', to='main.HeaderValue'),
        ),
    ]
