# Generated by Django 3.0.4 on 2020-03-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_logstag'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsTagAssign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.IntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LogsLog')),
            ],
            options={
                'verbose_name': 'Logs Tag Assign',
                'verbose_name_plural': 'Logs Tags Assign',
            },
        ),
    ]
