# Generated by Django 3.0.6 on 2020-05-26 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200527_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsnote',
            options={'ordering': ['-id'], 'verbose_name': 'LogsNote', 'verbose_name_plural': 'LogsNotes'},
        ),
    ]
