# Generated by Django 3.0.4 on 2020-04-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_logstagassign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logstagassign',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.LogsTag'),
        ),
    ]
