# Generated by Django 3.0.6 on 2020-06-01 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200601_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logsnote',
            options={'ordering': ('-id',), 'verbose_name': 'LogsNote', 'verbose_name_plural': 'LogsNotes'},
        ),
        migrations.AlterModelOptions(
            name='logstag',
            options={'ordering': ('id',), 'verbose_name': 'Logs Tag', 'verbose_name_plural': 'Logs Tags'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-transaction',), 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
    ]
