# Generated by Django 3.0.6 on 2020-05-27 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200527_0020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logsnote',
            old_name='ip',
            new_name='visitor_ip',
        ),
    ]
