# Generated by Django 3.0.5 on 2020-05-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200423_1718'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logslog',
            unique_together=set(),
        ),
    ]
