# Generated by Django 3.0.5 on 2020-05-17 14:13

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200507_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logstag',
            name='value_cryteria',
            field=models.TextField(validators=[main.models.validate_regex]),
        ),
    ]
