# Generated by Django 3.0.6 on 2020-06-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200601_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headername',
            options={'ordering': ('header_name',)},
        ),
    ]
