# Generated by Django 3.0.5 on 2020-04-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200409_1228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logstag',
            options={'ordering': ['id'], 'verbose_name': 'Logs Tag', 'verbose_name_plural': 'Logs Tags'},
        ),
        migrations.RemoveField(
            model_name='logslog',
            name='server',
        ),
        migrations.AlterField(
            model_name='logslog',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
