# Generated by Django 3.0.6 on 2020-08-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200601_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headervalue',
            options={'ordering': ('header_value',)},
        ),
    ]
