# Generated by Django 3.0.6 on 2020-05-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200517_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogsNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderValue', to_field='header_value')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Transaction')),
            ],
            options={
                'verbose_name': 'LogsNote',
                'verbose_name_plural': 'LogsNotes',
            },
        ),
    ]
