# Generated by Django 3.0.6 on 2020-05-20 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_logsnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsnote',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.HeaderValue'),
        ),
        migrations.AlterField(
            model_name='logsnote',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Transaction'),
        ),
    ]
