# Generated by Django 3.0.6 on 2020-05-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200520_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logsnote',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Transaction'),
        ),
    ]
